/**
 * Express type extensions
 *
 * This file extends Express types to include custom properties
 * added by middleware.
 */

import { AuthenticatedUser } from '../interfaces/jwt.interface';

declare global {
  namespace Express {
    interface Request {
      /**
       * Unique request ID for tracing and correlation across logs
       * Generated by requestIdMiddleware or provided by client via X-Request-ID header
       */
      requestId?: string;

      /**
       * Authenticated user information (if using authentication middleware)
       */
      user?: AuthenticatedUser;

      /**
       * The JWT access token from the Authorization header
       * Stored for logout functionality
       */
      token?: string;
    }
  }
}
